"""Explicit column contract for the ClickHouse ``stk_factor_pro`` table.

Generated from the DDL snapshot ``schema/clickhouse/ashare__stk_factor_pro.sql``
(CLICKHOUSE_ITERATION_PLAN.md P0.1 / P1.1), whose column order is authoritative.
The ClickHouse loader SELECTs exactly this list instead of ``SELECT *`` so a
schema change fails loudly at query time instead of silently leaking new
unannotated columns into the backtest/tool envelope (Flow-B closure).

Keep in sync with the DDL snapshot: when the snapshot gains or loses columns,
regenerate this tuple in the same order and refresh ``comments.yaml`` coverage.
"""

from __future__ import annotations

STK_FACTOR_PRO_COLUMNS: tuple[str, ...] = (
    "ts_code",
    "trade_date",
    "open",
    "open_hfq",
    "high",
    "high_hfq",
    "low",
    "low_hfq",
    "close",
    "close_hfq",
    "change",
    "pct_chg",
    "vol",
    "amount",
    "turnover_rate",
    "turnover_rate_f",
    "volume_ratio",
    "pe",
    "pe_ttm",
    "pb",
    "ps",
    "ps_ttm",
    "dv_ratio",
    "dv_ttm",
    "total_share",
    "float_share",
    "free_share",
    "total_mv",
    "circ_mv",
    "adj_factor",
    "asi_bfq",
    "asi_hfq",
    "asit_bfq",
    "asit_hfq",
    "atr_bfq",
    "atr_hfq",
    "bbi_bfq",
    "bbi_hfq",
    "bias1_bfq",
    "bias1_hfq",
    "bias2_bfq",
    "bias2_hfq",
    "bias3_bfq",
    "bias3_hfq",
    "boll_lower_bfq",
    "boll_lower_hfq",
    "boll_mid_bfq",
    "boll_mid_hfq",
    "boll_upper_bfq",
    "boll_upper_hfq",
    "brar_ar_bfq",
    "brar_ar_hfq",
    "brar_br_bfq",
    "brar_br_hfq",
    "cci_bfq",
    "cci_hfq",
    "cr_bfq",
    "cr_hfq",
    "dfma_dif_bfq",
    "dfma_dif_hfq",
    "dfma_difma_bfq",
    "dfma_difma_hfq",
    "dmi_adx_bfq",
    "dmi_adx_hfq",
    "dmi_adxr_bfq",
    "dmi_adxr_hfq",
    "dmi_mdi_bfq",
    "dmi_mdi_hfq",
    "dmi_pdi_bfq",
    "dmi_pdi_hfq",
    "downdays",
    "updays",
    "dpo_bfq",
    "dpo_hfq",
    "madpo_bfq",
    "madpo_hfq",
    "ema_bfq_10",
    "ema_bfq_20",
    "ema_bfq_250",
    "ema_bfq_30",
    "ema_bfq_5",
    "ema_bfq_60",
    "ema_bfq_90",
    "ema_hfq_10",
    "ema_hfq_20",
    "ema_hfq_250",
    "ema_hfq_30",
    "ema_hfq_5",
    "ema_hfq_60",
    "ema_hfq_90",
    "ema_qfq_10",
    "ema_qfq_20",
    "ema_qfq_250",
    "ema_qfq_30",
    "ema_qfq_5",
    "ema_qfq_60",
    "ema_qfq_90",
    "emv_bfq",
    "emv_hfq",
    "maemv_bfq",
    "maemv_hfq",
    "expma_12_bfq",
    "expma_12_hfq",
    "expma_50_bfq",
    "expma_50_hfq",
    "kdj_bfq",
    "kdj_hfq",
    "kdj_d_bfq",
    "kdj_d_hfq",
    "kdj_k_bfq",
    "kdj_k_hfq",
    "ktn_down_bfq",
    "ktn_down_hfq",
    "ktn_mid_bfq",
    "ktn_mid_hfq",
    "ktn_upper_bfq",
    "ktn_upper_hfq",
    "lowdays",
    "topdays",
    "ma_bfq_10",
    "ma_bfq_20",
    "ma_bfq_250",
    "ma_bfq_30",
    "ma_bfq_5",
    "ma_bfq_60",
    "ma_bfq_90",
    "ma_hfq_10",
    "ma_hfq_20",
    "ma_hfq_250",
    "ma_hfq_30",
    "ma_hfq_5",
    "ma_hfq_60",
    "ma_hfq_90",
    "ma_qfq_10",
    "ma_qfq_20",
    "ma_qfq_250",
    "ma_qfq_30",
    "ma_qfq_5",
    "ma_qfq_60",
    "ma_qfq_90",
    "macd_bfq",
    "macd_hfq",
    "macd_dea_bfq",
    "macd_dea_hfq",
    "macd_dif_bfq",
    "macd_dif_hfq",
    "mass_bfq",
    "mass_hfq",
    "ma_mass_bfq",
    "ma_mass_hfq",
    "mfi_bfq",
    "mfi_hfq",
    "mtm_bfq",
    "mtm_hfq",
    "mtmma_bfq",
    "mtmma_hfq",
    "obv_bfq",
    "obv_hfq",
    "psy_bfq",
    "psy_hfq",
    "psyma_bfq",
    "psyma_hfq",
    "roc_bfq",
    "roc_hfq",
    "maroc_bfq",
    "maroc_hfq",
    "rsi_bfq_12",
    "rsi_bfq_24",
    "rsi_bfq_6",
    "rsi_hfq_12",
    "rsi_hfq_24",
    "rsi_hfq_6",
    "rsi_qfq_12",
    "rsi_qfq_24",
    "rsi_qfq_6",
    "taq_down_bfq",
    "taq_down_hfq",
    "taq_mid_bfq",
    "taq_mid_hfq",
    "taq_up_bfq",
    "taq_up_hfq",
    "trix_bfq",
    "trix_hfq",
    "trma_bfq",
    "trma_hfq",
    "vr_bfq",
    "vr_hfq",
    "wr_bfq",
    "wr_hfq",
    "wr1_bfq",
    "wr1_hfq",
    "xsii_td1_bfq",
    "xsii_td1_hfq",
    "xsii_td2_bfq",
    "xsii_td2_hfq",
    "xsii_td3_bfq",
    "xsii_td3_hfq",
    "xsii_td4_bfq",
    "xsii_td4_hfq",
)


def stk_factor_pro_column_sql() -> str:
    """Return the backtick-quoted column list for use in SELECT statements.

    Every column is quoted so reserved-looking names (e.g. ``change``) are
    unambiguous; ordering follows the DDL snapshot deterministically.
    """
    return ", ".join(f"`{column}`" for column in STK_FACTOR_PRO_COLUMNS)
