"""Rendered artifacts for one tenant: env file, channels config, compose file.

Pure rendering — no docker, no filesystem writes, no secrets of its own (the
caller passes the generated key in). Kept apart from :mod:`router.provision`
so the shapes can be read and tested as templates.

``opencode.json`` is deliberately NOT rendered here: the existing
``config/opencode.json.tmpl`` + ``render_config.py`` pipeline owns it
(``entrypoint.sh`` renders it at container start, compiled against the
tool-governance manifest). Provisioning only supplies the environment that
pipeline reads, so the governance surface is never forked.
"""

from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:  # annotations only: spec.py imports COMPOSE_FILENAME from here
    from .spec import TenantSpec

# Operator-shared model/data-source credentials only. Per-tenant secrets
# (API_AUTH_KEY, OPENCODE_SERVER_PASSWORD, API_ALLOWED_HOSTS) and IM bot
# credentials are NEVER passed through: the first two are generated per tenant
# and the third belongs in agent.json as a placeholder.
PASSTHROUGH_ENV: tuple[str, ...] = (
    "DASHSCOPE_API_KEY",
    "DASHSCOPE_BASE_URL",
    "CLICKHOUSE_HOST",
    "CLICKHOUSE_PORT",
    "CLICKHOUSE_DATABASE",
    "CLICKHOUSE_USER",
    "CLICKHOUSE_PASSWORD",
    "CLICKHOUSE_LLM_USER",
    "CLICKHOUSE_LLM_PASSWORD",
    "TUSHARE_TOKEN",
)

# B5 skeleton: every stateful path under the volume-mounted /home/opencode.
HOME_SKELETON: tuple[str, ...] = (
    ".vibe-trading",
    ".vibe-trading/.vt-memory",
    ".vibe-trading/sessions",
    ".vibe-trading/runs",
    ".vibe-trading/uploads",
    ".vibe-trading/goals",
    ".vibe-trading/workspace",
    ".vibe-trading/channels",
    ".opencode",
    ".local/share/opencode",
    ".local/state",
    ".cache",
)

PLACEHOLDER = "__PROVISION_PLACEHOLDER_{tenant}_{field}__"
COMPOSE_FILENAME = "docker-compose.yml"
FLEET_FILENAME = "fleet.yml"


def render_env(spec: TenantSpec, api_key: str, serve_password: str) -> str:
    """Render the tenant's env file (the container's ``env_file``)."""
    lines = [
        f"# Generated by provision_tenant.py for tenant '{spec.tenant_id}'. chmod 600.",
        "# NEVER commit this file; it carries the tenant's API auth key.",
        "",
        "# --- tenant gateway auth (D9/B2: fail-closed, entrypoint refuses to boot) ---",
        f"API_AUTH_KEY={api_key}",
        f"OPENCODE_SERVER_PASSWORD={serve_password}",
        "# The router PRESERVES the public Host, so the gateway must trust it.",
        f"API_ALLOWED_HOSTS={spec.public_host},localhost",
        "",
        "# --- frontend watchdog input (settings_routes.py:397; T15 kept 90) ---",
        f"VIBE_TRADING_SSE_TIMEOUT={spec.sse_timeout_s}",
        "",
        "# --- D11: auto-title + swarm worker stay on the Python provider stack ---",
        "LANGCHAIN_PROVIDER=dashscope",
        "LANGCHAIN_MODEL_NAME=qwen3.8-max",
        "LANGCHAIN_TEMPERATURE=0.3",
        "",
        "# --- IM adapters: placeholders only, so nothing auto-starts (fail-closed) ---",
        "VIBE_TRADING_CHANNELS_AUTO_START=false",
    ]
    shared = read_dotenv(spec.base_env)
    passthrough = [(key, shared[key]) for key in PASSTHROUGH_ENV if shared.get(key)]
    if passthrough:
        lines += [
            "",
            "# --- operator-shared model/data-source credentials (passthrough) ---",
        ]
        lines += [f"{key}={value}" for key, value in passthrough]
    return "\n".join(lines) + "\n"


def render_channels(spec: TenantSpec) -> dict[str, object]:
    """Render the agent.json ``channels`` section with credential PLACEHOLDERS."""

    def placeholder(field_name: str) -> str:
        return PLACEHOLDER.format(tenant=spec.tenant_id.upper(), field=field_name)

    return {
        "channels": {
            "send_progress": True,
            "send_tool_hints": False,
            "reply_timeout_s": 600.0,
            # Empty operators list = fail closed: IM /pairing is rejected until
            # the tenant names its operators.
            "operators": [],
            "telegram": {
                "enabled": False,
                "token": placeholder("TELEGRAM_BOT_TOKEN"),
                "allow_from": [],
                "streaming": True,
            },
            "dingtalk": {
                "enabled": False,
                "client_id": placeholder("DINGTALK_CLIENT_ID"),
                "client_secret": placeholder("DINGTALK_CLIENT_SECRET"),
                "allow_from": [],
            },
            "feishu": {
                "enabled": False,
                "app_id": placeholder("FEISHU_APP_ID"),
                "app_secret": placeholder("FEISHU_APP_SECRET"),
                "allow_from": [],
            },
        }
    }


def render_compose(spec: TenantSpec) -> str:
    """Render the per-tenant compose file (T12 reuses it as the fleet unit)."""
    cron_state, cron_logs = spec.cron_volumes
    return f"""# Generated by provision_tenant.py — tenant '{spec.tenant_id}'.
# One tenant = one full-stack T10 container (gateway 8080 public, serve 4096
# internal). Start: docker compose -f {spec.compose_file} up -d
name: {spec.container_name}
services:
  {spec.container_name}:
    image: {spec.image}
    container_name: {spec.container_name}
    platform: {spec.platform}
    restart: unless-stopped
    ports:
      - "{spec.host_port}:8080"
    env_file:
      - {spec.env_file}
    environment:
      - TZ=Asia/Shanghai
      - VIBE_TRADING_HOME=/home/opencode/.vibe-trading
      - VT_MEMORY_BASE_DIR=/home/opencode/.vibe-trading/.vt-memory
      - VIBE_TRADING_ENGINE=opencode
      - OPENCODE_BASE_URL=http://127.0.0.1:4096
      - GATEWAY_PORT=8080
    volumes:
      - {spec.home_volume}:/home/opencode
      - {cron_state}:/workspace/cron_jobs/state
      - {cron_logs}:/workspace/cron_jobs/logs
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '2.0'
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s

volumes:
  {spec.home_volume}:
    external: true
  {cron_state}:
    external: true
  {cron_logs}:
    external: true
"""


def render_fleet(out_dir: Path, tenant_ids: Iterable[str]) -> str:
    """Render the fleet compose that ``include``s every tenant's own file."""
    includes = "\n".join(
        f"  - path: {out_dir / tenant_id / COMPOSE_FILENAME}"
        for tenant_id in sorted(tenant_ids)
    )
    return f"# Generated by provision_tenant.py\nname: vt-tenant-fleet\ninclude:\n{includes}\n"


def read_dotenv(path: Path | None) -> dict[str, str]:
    """Parse a flat KEY=VALUE dotenv file (no shell semantics, no interpolation)."""
    if path is None or not path.exists():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values
